s = input("Enter the string ")
print(s[:5:])
print(s[2:5:])
print(s[::-1])
print(s*2)
print(s.capitalize())
print(s.find("he"))
print(s.casefold())
print(s.center(3,'s'))
print(s.split('h'))
print(s.islower())
print(s.isupper())
print(s.upper())
print(s.lower())